# Generated by Django 4.2.4 on 2023-08-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.students'),
            preserve_default=False,
        ),
    ]
